// Shared Constants for Cricket Auction

export const roleImages = {
  Batsman: "/images/roles/Batsman.png",
  Bowler: "/images/roles/Bowler.png",
  Wicketkeeper: "/images/roles/Wicketkeeper.png",
  "All-Rounder": "/images/roles/All-Rounder.png",
};

export const FALLBACK_IMAGE = "/images/players/fallback.png";

export const initialIplTeams = [
  {
    id: 1,
    name: "Chennai Super Kings",
    shortName: "CSK",
    color: "border-yellow-400",
    headerColor: "bg-yellow-500",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 2,
    name: "Rajasthan Royals",
    shortName: "RR",
    color: "border-pink-400",
    headerColor: "bg-pink-500",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 3,
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    color: "border-purple-800",
    headerColor: "bg-purple-800",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 4,
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    color: "border-orange-500",
    headerColor: "bg-orange-500",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 5,
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    color: "border-red-700",
    headerColor: "bg-red-700",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 6,
    name: "Delhi Capitals",
    shortName: "DC",
    color: "border-sky-600",
    headerColor: "bg-sky-600",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 7,
    name: "Punjab Kings",
    shortName: "PBKS",
    color: "border-red-500",
    headerColor: "bg-red-500",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 8,
    name: "Mumbai Indians",
    shortName: "MI",
    color: "border-blue-600",
    headerColor: "bg-blue-600",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 9,
    name: "Gujarat Titans",
    shortName: "GT",
    color: "border-blue-900",
    headerColor: "bg-blue-900",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
  {
    id: 10,
    name: "Lucknow Super Giants",
    shortName: "LSG",
    color: "border-cyan-400",
    headerColor: "bg-cyan-500",
    budget: 120,
    players: [],
    rtmCount: 6,
  },
];
