// Broadcast Television Skin Themes for Cricket Auction Simulator
// Provides authentic television broadcast styling packages: Star Sports Gold, JioCinema Neon Night, Classic 2008 Vintage Retro

export const BROADCAST_THEMES = {
  modern_dark: {
    id: "modern_dark",
    name: "IPL Dark Broadcast",
    shortName: "Default Dark",
    badge: "📺",
    bgClass: "bg-gray-950",
    headerBg: "bg-gray-900 border-gray-800",
    cardBg: "bg-gray-900 border-gray-800",
    accentColor: "yellow",
    primaryGradient: "from-yellow-500 to-amber-600",
    glowStyle: "shadow-yellow-500/20",
    liveTickerBg: "bg-yellow-500/10 border-yellow-500/30 text-yellow-300",
    scorecardHeader: "bg-gray-900 border-gray-800",
    fontFamily: "Outfit, sans-serif",
    description: "Official sleek dark tournament arena with gold and amber accents.",
  },
  star_sports: {
    id: "star_sports",
    name: "Star Sports Ultra Gold",
    shortName: "Star Sports",
    badge: "⭐",
    bgClass: "bg-gradient-to-b from-[#061129] via-[#091b42] to-[#040c1d]",
    headerBg: "bg-[#091b42]/90 border-blue-600/50 shadow-lg shadow-blue-900/40",
    cardBg: "bg-[#0a1f4d]/90 border-blue-500/40",
    accentColor: "amber",
    primaryGradient: "from-amber-400 via-yellow-400 to-yellow-500",
    glowStyle: "shadow-amber-400/30",
    liveTickerBg: "bg-gradient-to-r from-blue-950/80 to-blue-900/80 border-amber-400/60 text-amber-300",
    scorecardHeader: "bg-[#0a1f4d] border-amber-500/40",
    fontFamily: "Outfit, sans-serif",
    description: "Iconic television broadcast layout with royal blues, sharp golds, and studio glitz.",
  },
  jiocinema_neon: {
    id: "jiocinema_neon",
    name: "JioCinema Neon Night",
    shortName: "JioCinema Neon",
    badge: "⚡",
    bgClass: "bg-gradient-to-b from-[#09021a] via-[#12052b] to-[#050010]",
    headerBg: "bg-[#180838]/90 border-fuchsia-500/50 shadow-lg shadow-purple-900/50",
    cardBg: "bg-[#1b093f]/90 border-purple-500/40",
    accentColor: "fuchsia",
    primaryGradient: "from-fuchsia-500 via-pink-500 to-cyan-400",
    glowStyle: "shadow-fuchsia-500/40",
    liveTickerBg: "bg-gradient-to-r from-purple-950/90 to-fuchsia-950/80 border-fuchsia-400/70 text-cyan-300",
    scorecardHeader: "bg-[#1b093f] border-fuchsia-500/50",
    fontFamily: "Outfit, sans-serif",
    description: "Cyberpunk neon broadcast with electric magenta, cyan highlights, and dynamic energy.",
  },
  vintage_retro: {
    id: "vintage_retro",
    name: "Vintage 2008 Retro CRT",
    shortName: "2008 Retro",
    badge: "🕰️",
    bgClass: "bg-gradient-to-b from-[#181a1b] via-[#202324] to-[#121314]",
    headerBg: "bg-[#25282a] border-amber-700/60 shadow-md shadow-amber-950/50",
    cardBg: "bg-[#222527] border-amber-800/40",
    accentColor: "yellow",
    primaryGradient: "from-yellow-400 to-amber-600",
    glowStyle: "shadow-yellow-600/30",
    liveTickerBg: "bg-[#181a1b] border-amber-600/60 text-yellow-300 font-mono",
    scorecardHeader: "bg-[#25282a] border-amber-700/60",
    fontFamily: "'Courier New', monospace, Outfit",
    description: "Nostalgic 2008 inaugural season aesthetics with sepia-tinted gold and classic scorebug graphics.",
  },
};
